//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMISClientProfile
    {
        public short OEMID { get; set; }
        public string Descr { get; set; }
        public string ImageName { get; set; }
        public byte[] FeatureSet { get; set; }
        public System.DateTime AccessToDate { get; set; }
    
        public virtual ToolServiceUse ToolServiceUse { get; set; }
        public virtual TreeTranslation TreeTranslation { get; set; }
        public virtual ClientTool ClientTool { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocationsVehicle LocationsVehicle { get; set; }
        public virtual svcLog svcLog { get; set; }
        public virtual InvMgmtVINList InvMgmtVINList { get; set; }
        public virtual AspNetUserClientRole AspNetUserClientRole { get; set; }
        public virtual Tests_Core Tests_Core { get; set; }
        public virtual ToolAuthorization ToolAuthorization { get; set; }
        public virtual RegionTree RegionTree { get; set; }
    }
}
