//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientTool()
        {
            this.BMISClientProfiles = new HashSet<BMISClientProfile>();
        }
    
        public short ClientID { get; set; }
        public byte ToolType { get; set; }
        public string SerialNumber { get; set; }
        public string SoftwareVersionNumber { get; set; }
        public System.DateTime LastComm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMISClientProfile> BMISClientProfiles { get; set; }
        public virtual ToolAuthorization ToolAuthorization { get; set; }
        public virtual svcLog svcLog { get; set; }
        public virtual ToolServiceUse ToolServiceUse { get; set; }
        public virtual Tests_Core Tests_Core { get; set; }
    }
}
