//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationsVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationsVehicle()
        {
            this.BMISClientProfiles = new HashSet<BMISClientProfile>();
        }
    
        public short OEMID { get; set; }
        public string LocationID { get; set; }
        public string VIN { get; set; }
        public long VehicleMake { get; set; }
        public long VehicleModel { get; set; }
        public int ModelYear { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public System.DateTime FirstSeen { get; set; }
        public System.DateTime LastSeen { get; set; }
        public bool ExcludeVIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMISClientProfile> BMISClientProfiles { get; set; }
        public virtual InvMgmtVINList InvMgmtVINList { get; set; }
        public virtual Honda_Dealer_Vehicle_Inventory Honda_Dealer_Vehicle_Inventory { get; set; }
    }
}
