//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientTool> ClientTools { get; set; }
        public virtual DbSet<Honda_Dealer_Vehicle_Inventory> Honda_Dealer_Vehicle_Inventory { get; set; }
        public virtual DbSet<InvMgmtVINList> InvMgmtVINLists { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationsVehicle> LocationsVehicles { get; set; }
        public virtual DbSet<RegionTree> RegionTrees { get; set; }
        public virtual DbSet<svcLog> svcLogs { get; set; }
        public virtual DbSet<Tests_Core> Tests_Core { get; set; }
        public virtual DbSet<ToolServiceUse> ToolServiceUses { get; set; }
        public virtual DbSet<AspNetUserClientRole> AspNetUserClientRoles { get; set; }
        public virtual DbSet<BMISClientProfile> BMISClientProfiles { get; set; }
        public virtual DbSet<ToolAuthorization> ToolAuthorizations { get; set; }
        public virtual DbSet<TreeTranslation> TreeTranslations { get; set; }
    }
}
