//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionTree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionTree()
        {
            this.BMISClientProfiles = new HashSet<BMISClientProfile>();
            this.Locations = new HashSet<Location>();
            this.RegionTrees = new HashSet<RegionTree>();
        }
    
        public int NodeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int TypeID { get; set; }
        public string ItemID { get; set; }
        public int Lvl { get; set; }
        public string Path { get; set; }
        public short ClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMISClientProfile> BMISClientProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionTree> RegionTrees { get; set; }
        public virtual RegionTree RegionTree1 { get; set; }
    }
}
