//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class svcLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public svcLog()
        {
            this.BMISClientProfiles = new HashSet<BMISClientProfile>();
            this.ClientTools = new HashSet<ClientTool>();
        }
    
        public short ClientID { get; set; }
        public System.DateTime TestDatetime { get; set; }
        public string SerialNumber { get; set; }
        public int LogType { get; set; }
        public string Message { get; set; }
        public string ClientIP { get; set; }
        public string ClientHostName { get; set; }
        public string Firmware { get; set; }
        public Nullable<long> ServiceFamily { get; set; }
        public Nullable<long> ServiceFunction { get; set; }
        public string UserName { get; set; }
        public int ToolType { get; set; }
        public string LocationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMISClientProfile> BMISClientProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTool> ClientTools { get; set; }
    }
}
