//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests_Core
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tests_Core()
        {
            this.BMISClientProfiles = new HashSet<BMISClientProfile>();
            this.Locations = new HashSet<Location>();
            this.ClientTools = new HashSet<ClientTool>();
        }
    
        public short ClientID { get; set; }
        public string LocationID { get; set; }
        public System.DateTime TestDatetime { get; set; }
        public int TestIndex { get; set; }
        public string SerialNumber { get; set; }
        public string SoftwareVersionNumber { get; set; }
        public int SoftwareBuildNumber { get; set; }
        public string AlgorithmVersion { get; set; }
        public byte ToolType { get; set; }
        public string MacAddress { get; set; }
        public byte TestType { get; set; }
        public Nullable<byte> TestLocation { get; set; }
        public Nullable<byte> Language { get; set; }
        public decimal FinalMeasuredVoltage { get; set; }
        public int FinalMeasuredCapacity { get; set; }
        public string FinalDisplayedMeausredCap { get; set; }
        public byte BatteryDecision { get; set; }
        public Nullable<byte> BatteryStateOfCharge { get; set; }
        public Nullable<byte> BatteryStateOfHealth { get; set; }
        public Nullable<byte> BatterySohPassFailPoint { get; set; }
        public Nullable<byte> BatterySohMarginalPoint { get; set; }
        public byte BatteryUnits { get; set; }
        public string TechnicianID { get; set; }
        public Nullable<byte> BatteryPostType { get; set; }
        public Nullable<byte> BatteryLocation { get; set; }
        public Nullable<byte> BatteryVehicleLocation { get; set; }
        public Nullable<byte> BatteryType { get; set; }
        public Nullable<byte> TestApplication { get; set; }
        public Nullable<byte> VehicleType { get; set; }
        public decimal RatedVoltage { get; set; }
        public int RatedCapacity { get; set; }
        public string RatedCapacityPntext { get; set; }
        public Nullable<byte> SurfaceChargeDetected { get; set; }
        public Nullable<byte> ChargeQuestion { get; set; }
        public Nullable<byte> AboveFreezing { get; set; }
        public int BatteryTemperature { get; set; }
        public string BatteryTemperatureUnits { get; set; }
        public string Testcode1 { get; set; }
        public string Testcode2 { get; set; }
        public string Testcode3 { get; set; }
        public string VinNumber { get; set; }
        public string RoNumber { get; set; }
        public string DealerVehicleStockNumber { get; set; }
        public Nullable<System.DateTime> BatteryMfgDateCode { get; set; }
        public Nullable<int> BatteryAge { get; set; }
        public string RfidTagSn { get; set; }
        public string BatterySn { get; set; }
        public string BatteryUpc { get; set; }
        public string UserScreenAnswer1 { get; set; }
        public string UserScreenAnswer2 { get; set; }
        public string UserScreenAnswer3 { get; set; }
        public Nullable<byte> DeepScanResult { get; set; }
        public Nullable<System.Guid> ShopinfoKeyID { get; set; }
        public Nullable<System.Guid> UserScreensKeyID { get; set; }
        public Nullable<System.Guid> CouponsKeyID { get; set; }
        public Nullable<System.Guid> DmmKeyID { get; set; }
        public Nullable<System.Guid> CableDropKeyID { get; set; }
        public Nullable<System.Guid> ChargingTestKeyID { get; set; }
        public Nullable<System.Guid> SystemTestKeyID { get; set; }
        public Nullable<decimal> PositiveCableResistance { get; set; }
        public Nullable<decimal> NegativeCableResistance { get; set; }
        public Nullable<long> VehicleMake { get; set; }
        public Nullable<long> VehicleModel { get; set; }
        public Nullable<System.DateTime> TransmittedOn { get; set; }
        public Nullable<System.DateTime> ImportedOn { get; set; }
        public string SrcFileName { get; set; }
        public Nullable<int> VehicleYear { get; set; }
        public string DistributorNumber { get; set; }
        public Nullable<byte> WasBatteryOriginal { get; set; }
        public Nullable<long> VehicleMileage { get; set; }
        public Nullable<byte> DCAResults { get; set; }
        public Nullable<byte> DCAStopCase { get; set; }
        public Nullable<decimal> DCAVoltageSlope { get; set; }
        public Nullable<decimal> DCAVoltageDrop { get; set; }
        public string VehicleIDNumber { get; set; }
        public Nullable<byte> VinCaptureMethod { get; set; }
        public Nullable<byte> VehicleTechnologyType { get; set; }
        public Nullable<byte> VehicleMileageUnits { get; set; }
        public Nullable<int> VehicleColor { get; set; }
        public string CustomerEmail { get; set; }
        public string VehicleLicensePlate { get; set; }
        public bool IsAddedToDecisionCounts { get; set; }
        public bool IsAddedToProcessPerformanceCounts { get; set; }
        public Nullable<byte> ConductanceDecision { get; set; }
        public Nullable<int> EngineTemperature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMISClientProfile> BMISClientProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTool> ClientTools { get; set; }
    }
}
